[package]
name = "lofi"
version = "0.1.0"
authors = ["Who23"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.9.0"
termion = "*"